name: Test trigger

on:
  push:
    branches:
      - main
      #     - master
  pull_request:
      

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8.8
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        set -eux
        conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
        pip install -r requirements.txt
        pip install black==19.10b0
    - name: Test with pytest
      run: |
        conda install pytest
        pytest test
        pytest new_folder/test
